# Generated by Django 6.0.1 on 2026-01-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='avg_buy_price',
            field=models.FloatField(default=0),
        ),
    ]
